### ISSUE TITLE
Minor spelling issue

### ISSUE THREAD

**Issue by jtaylor54** [seesser/InvertPWM#1]
In a future update you should change all occurrences of duty_cylce to duty_cycle . Thanks for creating this.

**Comment by seesser** [comment]
Will do,  I will be updating the script today with a working power stepdown logic attached so I will look for that before uploading.   Thank you,

**Comment by seesser** [comment]
Updated the code.  I changed the duty_cylce to frequency.  This spelling error is also in the GPIOPWM actor.  I also added InvertLogic to the code.  This logic only works with InvertPWM.

Thank you and please let me know of any other errors or ideas to improve the Plugins.
